{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "609af68a",
   "metadata": {
    "vscode": {
     "languageId": "plaintext"
    }
   },
   "outputs": [],
   "source": [
    "#!/usr/bin/env python\n",
    "# orchestrator.py\n",
    "import pathlib, subprocess, pandas as pd\n",
    "from linopy import Model  # only for reading PyPSA duals easily\n",
    "from pypsa import Network\n",
    "\n",
    "MAX_ITERS   = 30\n",
    "GAP_TARGET  = 0.5  # %\n",
    "YEAR_LIST   = [2025, 2030, 2040, 2050]\n",
    "\n",
    "def run_osemosys(iter_n: int) -> pd.DataFrame:\n",
    "    \"\"\"\n",
    "    1. Writes previous Benders cuts into capacities.inc\n",
    "    2. Calls the OSeMOSYS solver       (HiGHS/GLPK/Gurobi)\n",
    "    3. Returns a DataFrame with capacity per tech & year\n",
    "    \"\"\"\n",
    "    # 1. write cuts ─────────────────────────────────────────────\n",
    "    if iter_n > 0:\n",
    "        make_master_cut_file(iter_n)\n",
    "\n",
    "    # 2. solve\n",
    "    subprocess.run(\n",
    "        [\"highs\", \"model.gms\"], check=True, cwd=\"osemosys\"\n",
    "    )\n",
    "\n",
    "    # 3. parse results\n",
    "    caps = pd.read_csv(\"osemosys/results/capacity_summary.csv\")\n",
    "    return caps\n",
    "\n",
    "def build_and_run_pypsa(year: int, caps: pd.DataFrame):\n",
    "    \"\"\"\n",
    "    Build PyPSA network for `year` with OSeMOSYS capacities,\n",
    "    solve hourly dispatch, return objective & duals.\n",
    "    \"\"\"\n",
    "    net = Network(\"pypsa/base_network.nc\")\n",
    "    inject_capacities(net, caps.query(\"YEAR == @year\"))\n",
    "    net.optimize(solver_name=\"highs\", free_network=False)\n",
    "    duals = net.model.dual  # pandas Series (shadow prices)\n",
    "    obj   = net.objective\n",
    "    return obj, duals\n",
    "\n",
    "def generate_cuts(duals: pd.Series, caps: pd.DataFrame) -> str:\n",
    "    \"\"\"\n",
    "    Convert PyPSA duals into a linear Benders cut, return\n",
    "    it as GAMS-compatible text.\n",
    "    \"\"\"\n",
    "    coeffs = (\n",
    "        duals.groupby(\"gen_tech\").mean()  # example mapping\n",
    "        .reindex(caps.TECH.unique(), fill_value=0)\n",
    "    )\n",
    "    rhs = duals.attrs[\"primal_objective\"]\n",
    "    cut = \"BENDERSCUT .. Z >= \" + \" + \".join(\n",
    "        f\"{c:.6f} * CAP('{t}')\" for t, c in coeffs.items()\n",
    "    ) + f\" + {rhs:.2f} ;\\n\"\n",
    "    return cut\n",
    "\n",
    "# ─────────────────────────── loop ──────────────────────────────\n",
    "upper_bound = float(\"inf\")\n",
    "lower_bound = -float(\"inf\")\n",
    "\n",
    "for it in range(1, MAX_ITERS + 1):\n",
    "    caps = run_osemosys(it)\n",
    "    total_sub_obj = 0.0\n",
    "    cuts_text = []\n",
    "\n",
    "    for yr in YEAR_LIST:\n",
    "        obj, duals = build_and_run_pypsa(yr, caps)\n",
    "        total_sub_obj += obj\n",
    "        cuts_text.append(generate_cuts(duals, caps.query(\"YEAR == @yr\")))\n",
    "\n",
    "    upper_bound = min(upper_bound, total_sub_obj)   # incumbent\n",
    "    lower_bound = max(lower_bound, caps[\"NPC\"].sum())  # master LB\n",
    "\n",
    "    gap = 100 * (upper_bound - lower_bound) / upper_bound\n",
    "    print(f\"iter {it:02d}  LB={lower_bound:.1f}  UB={upper_bound:.1f}  gap={gap:.2f}%\")\n",
    "\n",
    "    if gap < GAP_TARGET:\n",
    "        print(\"Converged\")\n",
    "        break\n",
    "\n",
    "    store_cuts(cuts_text)              # append to cut_db.sqlite\n"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
